### PR TITLE
Role ComboBox options contain only roles for which there are no corresponding role mappings

### PR DESCRIPTION
**Pull request by sergibondarenko**
This closes https://floragunn.atlassian.net/browse/ITT-2214

Instead of graying out options, I made the ComboBox contain only roles for which there are no corresponding role mappings. 

To check this PR
1. Go to Create Role Mapping page
2. Select Role ComboBox
3. See the existing role mappings are not among the options
4. Create a role mapping
5. Go back to Create Role Mapping page
6. See the existing role mappings are not among the options
7. Eventually, there are no options if you created role mappings for all existing roles

Screenshot
Screenshot 2019-06-25 at 14 34 17

### CODE REVIEW

**Comment by sergibondarenko** [comment]
@jochenkressin what do you think about this solution?

**Comment by sergibondarenko** [comment]
> Code looks ready to merge.
> 
> I personally prefer showing all roles, and greying out those that are already in use.
> To me it is normally a bit clearer then that there is some constraint that prevents me from selecting the used roles, and I don't wonder why they are missing from the list.
> But I'll let you and @jochenkressin decide.

What if we have a huge amount of roles? In this case, to minimize scrolling, we should divide the combobox options into 2 sections I guess. Anyway, I think displaying only available options is clear enough.

**Comment by jochenkressin** [comment]
Personally, I would also opt for displaying unavailable roles greyed out. But we can go ahead and merge this PR and then collect feedback from the users.

**Comment by sergibondarenko** [comment]
I close this in favor of PR https://github.com/floragunncom/search-guard-kibana-plugin/pull/237

**Pull request closed without merging**
