### PR TITLE
ITT-2152 - Take non default space into account in nextUrl when redire…

### PR DESCRIPTION
**Pull request by mgustafsson1**
This PR makes sure that the space prefix is available in the nextUrl when redirecting an unauthenticated request.

Fixes https://github.com/floragunncom/search-guard/issues/699

### CODE REVIEW

**Comment by mgustafsson1** [comment]
This needs to be backported all the way to 6.5

**Comment by mgustafsson1** [comment]
Merged into
master,
7.0.x, es-7.0.0, es-7.0.1
7.1.x, es-7.1.0
6.x
6.8, es-6.8.0
6.7, es-6.7.0, es-6.7.1, es-6.7.2
6.6, es-6.6.0, es-6.6.1, es-6.6.2
6.5, es-6.5.1, es-6.5.2, es-6.5.3, es-6.5.4

**Comment by Alsheh** [comment]
@mgustafsson1 thanks for submitting this fix! What release will have these updates?

**Comment by mgustafsson1** [comment]
@Alsheh This fix has been released for versions 6 and 7. Here are the release notes:
https://docs.search-guard.com/latest/changelog-kibana-7.x-35_1_0
https://docs.search-guard.com/6.x-25/changelog-kibana-6.x-18.4

Hope this helps!

**Pull request merged**
